name: Draft PDF
on: 
  push:
    branches:
      - main  # or any other branch you want to trigger this workflow on

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v0.1.0  # replace 'v0.1.0' with the correct version if available
        with:
          journal: jose
          paper-path: paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf  # Make sure the path is correct where the PDF is generated
