name: Build Paper

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile paper
      uses: openjournals/joss-pdf@v1
      with:
        source: paper/paper.md
